# Generated by Django 2.1.3 on 2018-11-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
